name: Build and deploy Python project to Azure Function App - DEV-SE-Hue-FuncApp

on:
  push:
    branches:
      - main
  workflow_dispatch: 

env:
  AZURE_FUNCTIONAPP_NAME: DEV-SE-Hue-FuncApp
  AZURE_FUNCTIONAPP_PACKAGE_PATH: .
  PYTHON_VERSION: "3.13"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D96F9CC9AF42407DA890CE36A2919C24 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_599AC43D355A47B4AFF5F0A5A9E689B0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B7690027357341D1A8096740A4ACB9B5 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
          respect-funcignore: true
          remote-build: true
